### ISSUE TITLE
@admin timeslice=0 crash

### ISSUE THREAD

**Issue by kaganar** [brazilofmux/tinymux#691]
On MUX2.7 from #1 with a blank DB, @admin timeslice=0 crashes. I've not had an opportunity to test it on newer MUXen.

**Comment by brazilofmux** [comment]
I would expect that to crash with a division by zero even on the latest version. It's using the generic cf_seconds() routine to parse the argument, and this has no sense of whether a zero value is valid for that purpose or not. Probably should write a non-generic cf_timeslice which uses cf_seconds and then does extra validation.
