### ISSUE TITLE
netcommon.cpp build error

### ISSUE THREAD

**Issue by Talmeron** [brazilofmux/tinymux#692]
Using latest Mint (also does it on Ubuntu Server)
g++ 5.4
Mysql server 5.7

Enabled Firanmux and inlinesql (yes, I know)

g++  -g -O      -DFIRANMUX   -DINLINESQL -I/usr/include/mysql  -c netcommon.cpp
netcommon.cpp: In function ‘void do_logged_out_internal(DESC*, int, const UTF8*)’:
netcommon.cpp:2686:41: error: invalid conversion from ‘const char*’ to ‘const UTF8* {aka const unsigned char*}’ [-fpermissive]
             queue_write_LEN(d, "\r\n", 2);
                                         ^
netcommon.cpp:417:6: note:   initializing argument 2 of ‘void queue_write_LEN(DESC*, const UTF8*, size_t)’
 void queue_write_LEN(DESC *d, const UTF8 *b, size_t n)
      ^
Makefile:177: recipe for target 'netcommon.o' failed
make: *** [netcommon.o] Error 1

**Comment by brazilofmux** [comment]
Fixed with 5929f81186262edbf9da0d934046c531801248e3.
